//! Bestiary. One hundred monster kinds organised easy-to-hard.
//! Host-owned read-only data. Each kind names an artificial-
//! intelligence archetype that the per-turn dispatcher routes to.
//!
//! The bestiary table is the data half of the monster system. The
//! code half is a small number of artificial-intelligence scripts
//! that the host invokes per monster per turn. Many monster kinds
//! share a script while varying their stats.

/// Visual silhouette used by the sprite renderer. The renderer
/// fills the silhouette with the kind's primary colour and accent.
/// Twelve silhouettes provide enough visual variety for the full
/// roster without requiring per-kind artwork.
#[derive(Clone, Copy, Debug)]
pub enum Shape {
    Tiny,
    Small,
    Humanoid,
    Brute,
    Serpent,
    Insect,
    Skeleton,
    Mage,
    Ghost,
    Slime,
    Dragon,
    Boss,
}

/// Artificial-intelligence archetype. The host maps each archetype
/// to a Keleusma script name. Shared archetypes across multiple
/// kinds is intentional and was confirmed during the design
/// clarification.
#[derive(Clone, Copy, Debug)]
pub enum AiKind {
    Idle,
    Wander,
    Chaser,
    Smart,
    Sleeper,
    Ranged,
    Fast,
    Boss,
}

/// A single bestiary entry. Stats are read-only. Per-monster
/// mutable state (current hit points, position, archetype-specific
/// state) lives elsewhere in [`crate::world::Monster`].
pub struct MonsterKind {
    pub name: &'static str,
    pub shape: Shape,
    pub primary: (u8, u8, u8),
    pub accent: (u8, u8, u8),
    pub max_hp: i32,
    pub skill: i32,
    pub evasion: i32,
    pub damage: i32,
    pub armor: i32,
    pub ai: AiKind,
    /// Lowest floor on which this kind appears as the floor's
    /// favourite. Random-pool spawns may still draw the kind on
    /// any floor at or beyond this depth.
    pub first_floor: u32,
    /// Experience-less progression. Kills add this much to the
    /// score in addition to any gold the kind drops.
    pub score: u32,
}

const fn rgb(r: u8, g: u8, b: u8) -> (u8, u8, u8) {
    (r, g, b)
}

/// The bestiary. One hundred entries indexed by kind identifier
/// zero through ninety-nine. Sorted approximately by ascending
/// difficulty so floor N defaults to entry N - 1 as its favourite
/// when the host generates a floor.
pub const BESTIARY: [MonsterKind; 100] = [
    // -- Floors 1 through 10. Vermin and unskilled humanoids. --
    MonsterKind {
        name: "Sewer Rat",
        shape: Shape::Tiny,
        primary: rgb(120, 90, 60),
        accent: rgb(60, 40, 30),
        max_hp: 3,
        skill: 0,
        evasion: 1,
        damage: 1,
        armor: 0,
        ai: AiKind::Chaser,
        first_floor: 1,
        score: 1,
    },
    MonsterKind {
        name: "Giant Centipede",
        shape: Shape::Insect,
        primary: rgb(140, 60, 60),
        accent: rgb(60, 20, 20),
        max_hp: 4,
        skill: 1,
        evasion: 1,
        damage: 2,
        armor: 0,
        ai: AiKind::Chaser,
        first_floor: 2,
        score: 2,
    },
    MonsterKind {
        name: "Cave Bat",
        shape: Shape::Tiny,
        primary: rgb(60, 60, 80),
        accent: rgb(30, 30, 40),
        max_hp: 4,
        skill: 1,
        evasion: 4,
        damage: 1,
        armor: 0,
        ai: AiKind::Fast,
        first_floor: 3,
        score: 2,
    },
    MonsterKind {
        name: "Spotted Newt",
        shape: Shape::Tiny,
        primary: rgb(60, 140, 80),
        accent: rgb(220, 200, 60),
        max_hp: 5,
        skill: 1,
        evasion: 1,
        damage: 1,
        armor: 0,
        ai: AiKind::Idle,
        first_floor: 4,
        score: 2,
    },
    MonsterKind {
        name: "Cave Spider",
        shape: Shape::Insect,
        primary: rgb(40, 30, 30),
        accent: rgb(180, 40, 40),
        max_hp: 6,
        skill: 2,
        evasion: 2,
        damage: 2,
        armor: 0,
        ai: AiKind::Sleeper,
        first_floor: 5,
        score: 3,
    },
    MonsterKind {
        name: "Mongrel Cur",
        shape: Shape::Small,
        primary: rgb(100, 80, 60),
        accent: rgb(60, 50, 40),
        max_hp: 8,
        skill: 2,
        evasion: 2,
        damage: 2,
        armor: 0,
        ai: AiKind::Chaser,
        first_floor: 6,
        score: 3,
    },
    MonsterKind {
        name: "Brown Snake",
        shape: Shape::Serpent,
        primary: rgb(120, 100, 60),
        accent: rgb(60, 50, 30),
        max_hp: 7,
        skill: 2,
        evasion: 2,
        damage: 3,
        armor: 0,
        ai: AiKind::Sleeper,
        first_floor: 7,
        score: 3,
    },
    MonsterKind {
        name: "Gnoll Pup",
        shape: Shape::Humanoid,
        primary: rgb(140, 100, 60),
        accent: rgb(60, 40, 20),
        max_hp: 9,
        skill: 3,
        evasion: 2,
        damage: 2,
        armor: 0,
        ai: AiKind::Wander,
        first_floor: 8,
        score: 4,
    },
    MonsterKind {
        name: "Restless Skeleton",
        shape: Shape::Skeleton,
        primary: rgb(220, 220, 200),
        accent: rgb(80, 80, 80),
        max_hp: 10,
        skill: 3,
        evasion: 1,
        damage: 3,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 9,
        score: 5,
    },
    MonsterKind {
        name: "Kobold Sneak",
        shape: Shape::Humanoid,
        primary: rgb(140, 60, 40),
        accent: rgb(40, 20, 20),
        max_hp: 11,
        skill: 3,
        evasion: 3,
        damage: 3,
        armor: 0,
        ai: AiKind::Chaser,
        first_floor: 10,
        score: 5,
    },
    // -- Floors 11 through 20. Tribal humanoids and small beasts. --
    MonsterKind {
        name: "Goblin Sneak",
        shape: Shape::Humanoid,
        primary: rgb(80, 140, 60),
        accent: rgb(40, 60, 30),
        max_hp: 12,
        skill: 4,
        evasion: 3,
        damage: 3,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 11,
        score: 6,
    },
    MonsterKind {
        name: "Giant Ant",
        shape: Shape::Insect,
        primary: rgb(140, 40, 40),
        accent: rgb(60, 20, 20),
        max_hp: 13,
        skill: 4,
        evasion: 2,
        damage: 3,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 12,
        score: 6,
    },
    MonsterKind {
        name: "Giant Beetle",
        shape: Shape::Insect,
        primary: rgb(40, 140, 60),
        accent: rgb(20, 60, 30),
        max_hp: 15,
        skill: 4,
        evasion: 1,
        damage: 3,
        armor: 2,
        ai: AiKind::Chaser,
        first_floor: 13,
        score: 7,
    },
    MonsterKind {
        name: "Stirge",
        shape: Shape::Tiny,
        primary: rgb(140, 80, 100),
        accent: rgb(60, 30, 40),
        max_hp: 10,
        skill: 5,
        evasion: 4,
        damage: 4,
        armor: 0,
        ai: AiKind::Fast,
        first_floor: 14,
        score: 7,
    },
    MonsterKind {
        name: "Acolyte Zombie",
        shape: Shape::Humanoid,
        primary: rgb(100, 140, 80),
        accent: rgb(40, 60, 30),
        max_hp: 16,
        skill: 4,
        evasion: 1,
        damage: 4,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 15,
        score: 8,
    },
    MonsterKind {
        name: "Hobbit Thug",
        shape: Shape::Small,
        primary: rgb(140, 100, 80),
        accent: rgb(60, 40, 30),
        max_hp: 14,
        skill: 5,
        evasion: 3,
        damage: 4,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 16,
        score: 8,
    },
    MonsterKind {
        name: "Hyena",
        shape: Shape::Small,
        primary: rgb(160, 140, 80),
        accent: rgb(80, 60, 30),
        max_hp: 16,
        skill: 5,
        evasion: 3,
        damage: 4,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 17,
        score: 9,
    },
    MonsterKind {
        name: "Gnome Sapper",
        shape: Shape::Humanoid,
        primary: rgb(100, 100, 160),
        accent: rgb(220, 200, 60),
        max_hp: 14,
        skill: 6,
        evasion: 4,
        damage: 5,
        armor: 1,
        ai: AiKind::Smart,
        first_floor: 18,
        score: 10,
    },
    MonsterKind {
        name: "Pixie Stinger",
        shape: Shape::Tiny,
        primary: rgb(220, 180, 220),
        accent: rgb(100, 60, 140),
        max_hp: 12,
        skill: 7,
        evasion: 6,
        damage: 4,
        armor: 0,
        ai: AiKind::Ranged,
        first_floor: 19,
        score: 10,
    },
    MonsterKind {
        name: "Giant Frog",
        shape: Shape::Small,
        primary: rgb(80, 160, 60),
        accent: rgb(40, 80, 30),
        max_hp: 18,
        skill: 5,
        evasion: 2,
        damage: 5,
        armor: 1,
        ai: AiKind::Wander,
        first_floor: 20,
        score: 10,
    },
    // -- Floors 21 through 30. Drilled militants and trained beasts. --
    MonsterKind {
        name: "Goblin Warrior",
        shape: Shape::Humanoid,
        primary: rgb(60, 140, 40),
        accent: rgb(120, 60, 40),
        max_hp: 20,
        skill: 6,
        evasion: 3,
        damage: 5,
        armor: 2,
        ai: AiKind::Smart,
        first_floor: 21,
        score: 12,
    },
    MonsterKind {
        name: "Orc Whelp",
        shape: Shape::Humanoid,
        primary: rgb(100, 120, 80),
        accent: rgb(60, 40, 30),
        max_hp: 22,
        skill: 6,
        evasion: 2,
        damage: 6,
        armor: 2,
        ai: AiKind::Chaser,
        first_floor: 22,
        score: 12,
    },
    MonsterKind {
        name: "Imp",
        shape: Shape::Tiny,
        primary: rgb(200, 60, 60),
        accent: rgb(60, 30, 30),
        max_hp: 18,
        skill: 7,
        evasion: 5,
        damage: 6,
        armor: 1,
        ai: AiKind::Fast,
        first_floor: 23,
        score: 14,
    },
    MonsterKind {
        name: "Wraithling",
        shape: Shape::Ghost,
        primary: rgb(120, 120, 180),
        accent: rgb(60, 60, 100),
        max_hp: 20,
        skill: 7,
        evasion: 5,
        damage: 6,
        armor: 0,
        ai: AiKind::Chaser,
        first_floor: 24,
        score: 14,
    },
    MonsterKind {
        name: "Dire Wolf",
        shape: Shape::Brute,
        primary: rgb(80, 80, 100),
        accent: rgb(40, 40, 60),
        max_hp: 26,
        skill: 7,
        evasion: 4,
        damage: 7,
        armor: 1,
        ai: AiKind::Chaser,
        first_floor: 25,
        score: 15,
    },
    MonsterKind {
        name: "Werecat",
        shape: Shape::Humanoid,
        primary: rgb(140, 80, 60),
        accent: rgb(220, 200, 60),
        max_hp: 24,
        skill: 8,
        evasion: 5,
        damage: 7,
        armor: 1,
        ai: AiKind::Fast,
        first_floor: 26,
        score: 16,
    },
    MonsterKind {
        name: "Giant Scorpion",
        shape: Shape::Insect,
        primary: rgb(140, 100, 60),
        accent: rgb(60, 40, 30),
        max_hp: 28,
        skill: 8,
        evasion: 3,
        damage: 7,
        armor: 3,
        ai: AiKind::Chaser,
        first_floor: 27,
        score: 17,
    },
    MonsterKind {
        name: "Hobgoblin Captain",
        shape: Shape::Humanoid,
        primary: rgb(180, 60, 40),
        accent: rgb(60, 60, 60),
        max_hp: 30,
        skill: 9,
        evasion: 3,
        damage: 8,
        armor: 3,
        ai: AiKind::Smart,
        first_floor: 28,
        score: 18,
    },
    MonsterKind {
        name: "Ogre Whelp",
        shape: Shape::Brute,
        primary: rgb(120, 100, 80),
        accent: rgb(60, 40, 30),
        max_hp: 36,
        skill: 8,
        evasion: 1,
        damage: 9,
        armor: 2,
        ai: AiKind::Chaser,
        first_floor: 29,
        score: 20,
    },
    MonsterKind {
        name: "Carrion Crawler",
        shape: Shape::Serpent,
        primary: rgb(140, 140, 80),
        accent: rgb(60, 60, 30),
        max_hp: 30,
        skill: 9,
        evasion: 3,
        damage: 8,
        armor: 2,
        ai: AiKind::Sleeper,
        first_floor: 30,
        score: 18,
    },
    // -- Floors 31 through 40. Veteran captains and large beasts. --
    MonsterKind {
        name: "Gnoll Warlord",
        shape: Shape::Humanoid,
        primary: rgb(160, 100, 40),
        accent: rgb(40, 20, 20),
        max_hp: 34,
        skill: 10,
        evasion: 3,
        damage: 9,
        armor: 3,
        ai: AiKind::Smart,
        first_floor: 31,
        score: 22,
    },
    MonsterKind {
        name: "Orc Captain",
        shape: Shape::Humanoid,
        primary: rgb(80, 140, 60),
        accent: rgb(140, 40, 40),
        max_hp: 38,
        skill: 10,
        evasion: 3,
        damage: 9,
        armor: 3,
        ai: AiKind::Smart,
        first_floor: 32,
        score: 23,
    },
    MonsterKind {
        name: "Bugbear",
        shape: Shape::Brute,
        primary: rgb(120, 80, 60),
        accent: rgb(60, 40, 30),
        max_hp: 40,
        skill: 10,
        evasion: 2,
        damage: 10,
        armor: 3,
        ai: AiKind::Chaser,
        first_floor: 33,
        score: 24,
    },
    MonsterKind {
        name: "Werewolf",
        shape: Shape::Brute,
        primary: rgb(100, 80, 60),
        accent: rgb(180, 180, 180),
        max_hp: 42,
        skill: 11,
        evasion: 4,
        damage: 10,
        armor: 2,
        ai: AiKind::Fast,
        first_floor: 34,
        score: 26,
    },
    MonsterKind {
        name: "Brown Mold",
        shape: Shape::Slime,
        primary: rgb(120, 80, 40),
        accent: rgb(60, 40, 20),
        max_hp: 36,
        skill: 9,
        evasion: 0,
        damage: 10,
        armor: 4,
        ai: AiKind::Idle,
        first_floor: 35,
        score: 22,
    },
    MonsterKind {
        name: "Yellow Mold",
        shape: Shape::Slime,
        primary: rgb(180, 160, 60),
        accent: rgb(80, 60, 20),
        max_hp: 36,
        skill: 9,
        evasion: 0,
        damage: 11,
        armor: 4,
        ai: AiKind::Idle,
        first_floor: 36,
        score: 22,
    },
    MonsterKind {
        name: "Black Pudding",
        shape: Shape::Slime,
        primary: rgb(40, 40, 40),
        accent: rgb(20, 20, 20),
        max_hp: 44,
        skill: 9,
        evasion: 1,
        damage: 11,
        armor: 3,
        ai: AiKind::Wander,
        first_floor: 37,
        score: 26,
    },
    MonsterKind {
        name: "Gelatinous Cube",
        shape: Shape::Slime,
        primary: rgb(180, 200, 220),
        accent: rgb(80, 100, 120),
        max_hp: 50,
        skill: 8,
        evasion: 0,
        damage: 10,
        armor: 4,
        ai: AiKind::Wander,
        first_floor: 38,
        score: 28,
    },
    MonsterKind {
        name: "Ogre",
        shape: Shape::Brute,
        primary: rgb(140, 120, 80),
        accent: rgb(80, 60, 40),
        max_hp: 50,
        skill: 11,
        evasion: 1,
        damage: 12,
        armor: 3,
        ai: AiKind::Chaser,
        first_floor: 39,
        score: 30,
    },
    MonsterKind {
        name: "Cave Bear",
        shape: Shape::Brute,
        primary: rgb(120, 80, 60),
        accent: rgb(60, 40, 30),
        max_hp: 52,
        skill: 11,
        evasion: 2,
        damage: 12,
        armor: 3,
        ai: AiKind::Chaser,
        first_floor: 40,
        score: 30,
    },
    // -- Floors 41 through 50. Giants, trolls, and elementals. --
    MonsterKind {
        name: "Troll",
        shape: Shape::Brute,
        primary: rgb(80, 140, 80),
        accent: rgb(40, 60, 40),
        max_hp: 60,
        skill: 12,
        evasion: 2,
        damage: 13,
        armor: 3,
        ai: AiKind::Chaser,
        first_floor: 41,
        score: 36,
    },
    MonsterKind {
        name: "Young Hydra",
        shape: Shape::Serpent,
        primary: rgb(80, 100, 140),
        accent: rgb(40, 60, 80),
        max_hp: 64,
        skill: 12,
        evasion: 2,
        damage: 14,
        armor: 3,
        ai: AiKind::Chaser,
        first_floor: 42,
        score: 38,
    },
    MonsterKind {
        name: "Iron Statue",
        shape: Shape::Humanoid,
        primary: rgb(140, 140, 160),
        accent: rgb(80, 80, 100),
        max_hp: 58,
        skill: 10,
        evasion: 0,
        damage: 12,
        armor: 6,
        ai: AiKind::Idle,
        first_floor: 43,
        score: 32,
    },
    MonsterKind {
        name: "Salamander",
        shape: Shape::Serpent,
        primary: rgb(220, 100, 60),
        accent: rgb(120, 40, 20),
        max_hp: 60,
        skill: 13,
        evasion: 3,
        damage: 14,
        armor: 3,
        ai: AiKind::Ranged,
        first_floor: 44,
        score: 38,
    },
    MonsterKind {
        name: "Cyclops",
        shape: Shape::Brute,
        primary: rgb(160, 120, 80),
        accent: rgb(220, 60, 60),
        max_hp: 70,
        skill: 13,
        evasion: 1,
        damage: 16,
        armor: 4,
        ai: AiKind::Chaser,
        first_floor: 45,
        score: 42,
    },
    MonsterKind {
        name: "Manticore",
        shape: Shape::Dragon,
        primary: rgb(140, 80, 40),
        accent: rgb(60, 40, 20),
        max_hp: 70,
        skill: 13,
        evasion: 3,
        damage: 15,
        armor: 4,
        ai: AiKind::Ranged,
        first_floor: 46,
        score: 42,
    },
    MonsterKind {
        name: "Wyvern",
        shape: Shape::Dragon,
        primary: rgb(120, 60, 80),
        accent: rgb(60, 30, 40),
        max_hp: 72,
        skill: 14,
        evasion: 4,
        damage: 15,
        armor: 4,
        ai: AiKind::Fast,
        first_floor: 47,
        score: 44,
    },
    MonsterKind {
        name: "Lich Apprentice",
        shape: Shape::Mage,
        primary: rgb(100, 60, 180),
        accent: rgb(60, 30, 100),
        max_hp: 64,
        skill: 14,
        evasion: 3,
        damage: 14,
        armor: 3,
        ai: AiKind::Ranged,
        first_floor: 48,
        score: 44,
    },
    MonsterKind {
        name: "Wraith",
        shape: Shape::Ghost,
        primary: rgb(60, 60, 140),
        accent: rgb(30, 30, 80),
        max_hp: 60,
        skill: 14,
        evasion: 5,
        damage: 14,
        armor: 2,
        ai: AiKind::Smart,
        first_floor: 49,
        score: 44,
    },
    MonsterKind {
        name: "Specter",
        shape: Shape::Ghost,
        primary: rgb(140, 140, 200),
        accent: rgb(60, 60, 120),
        max_hp: 64,
        skill: 14,
        evasion: 5,
        damage: 14,
        armor: 2,
        ai: AiKind::Smart,
        first_floor: 50,
        score: 46,
    },
    // -- Floors 51 through 60. Demons, undead nobility, lesser dragons. --
    MonsterKind {
        name: "Vampire Spawn",
        shape: Shape::Humanoid,
        primary: rgb(140, 60, 60),
        accent: rgb(60, 30, 30),
        max_hp: 70,
        skill: 15,
        evasion: 4,
        damage: 15,
        armor: 3,
        ai: AiKind::Fast,
        first_floor: 51,
        score: 50,
    },
    MonsterKind {
        name: "Dire Bear",
        shape: Shape::Brute,
        primary: rgb(100, 60, 40),
        accent: rgb(60, 40, 20),
        max_hp: 80,
        skill: 14,
        evasion: 2,
        damage: 16,
        armor: 4,
        ai: AiKind::Chaser,
        first_floor: 52,
        score: 50,
    },
    MonsterKind {
        name: "Greater Imp",
        shape: Shape::Small,
        primary: rgb(220, 60, 60),
        accent: rgb(100, 30, 30),
        max_hp: 64,
        skill: 16,
        evasion: 6,
        damage: 15,
        armor: 3,
        ai: AiKind::Fast,
        first_floor: 53,
        score: 50,
    },
    MonsterKind {
        name: "Pit Fiend Whelp",
        shape: Shape::Humanoid,
        primary: rgb(180, 40, 40),
        accent: rgb(60, 20, 20),
        max_hp: 86,
        skill: 16,
        evasion: 3,
        damage: 17,
        armor: 5,
        ai: AiKind::Smart,
        first_floor: 54,
        score: 56,
    },
    MonsterKind {
        name: "Stone Giant",
        shape: Shape::Brute,
        primary: rgb(140, 140, 140),
        accent: rgb(80, 80, 80),
        max_hp: 100,
        skill: 14,
        evasion: 1,
        damage: 18,
        armor: 6,
        ai: AiKind::Chaser,
        first_floor: 55,
        score: 60,
    },
    MonsterKind {
        name: "Cloud Giant Adept",
        shape: Shape::Brute,
        primary: rgb(200, 200, 220),
        accent: rgb(100, 100, 140),
        max_hp: 96,
        skill: 15,
        evasion: 2,
        damage: 18,
        armor: 5,
        ai: AiKind::Smart,
        first_floor: 56,
        score: 60,
    },
    MonsterKind {
        name: "Frost Salamander",
        shape: Shape::Serpent,
        primary: rgb(140, 220, 220),
        accent: rgb(60, 100, 140),
        max_hp: 80,
        skill: 16,
        evasion: 3,
        damage: 17,
        armor: 4,
        ai: AiKind::Ranged,
        first_floor: 57,
        score: 60,
    },
    MonsterKind {
        name: "Fire Drake",
        shape: Shape::Dragon,
        primary: rgb(220, 100, 40),
        accent: rgb(120, 40, 20),
        max_hp: 90,
        skill: 16,
        evasion: 3,
        damage: 18,
        armor: 5,
        ai: AiKind::Fast,
        first_floor: 58,
        score: 64,
    },
    MonsterKind {
        name: "Black Drake",
        shape: Shape::Dragon,
        primary: rgb(40, 40, 40),
        accent: rgb(140, 140, 60),
        max_hp: 92,
        skill: 16,
        evasion: 3,
        damage: 18,
        armor: 5,
        ai: AiKind::Fast,
        first_floor: 59,
        score: 64,
    },
    MonsterKind {
        name: "Green Drake",
        shape: Shape::Dragon,
        primary: rgb(40, 140, 40),
        accent: rgb(120, 220, 40),
        max_hp: 94,
        skill: 17,
        evasion: 3,
        damage: 18,
        armor: 5,
        ai: AiKind::Fast,
        first_floor: 60,
        score: 66,
    },
    // -- Floors 61 through 70. Drakes, golems, and demon nobility. --
    MonsterKind {
        name: "White Drake",
        shape: Shape::Dragon,
        primary: rgb(220, 220, 220),
        accent: rgb(140, 200, 220),
        max_hp: 96,
        skill: 17,
        evasion: 3,
        damage: 19,
        armor: 5,
        ai: AiKind::Fast,
        first_floor: 61,
        score: 70,
    },
    MonsterKind {
        name: "Red Drake",
        shape: Shape::Dragon,
        primary: rgb(220, 60, 40),
        accent: rgb(120, 40, 20),
        max_hp: 100,
        skill: 17,
        evasion: 3,
        damage: 20,
        armor: 5,
        ai: AiKind::Fast,
        first_floor: 62,
        score: 72,
    },
    MonsterKind {
        name: "Iron Golem",
        shape: Shape::Brute,
        primary: rgb(160, 160, 180),
        accent: rgb(80, 80, 100),
        max_hp: 120,
        skill: 14,
        evasion: 0,
        damage: 20,
        armor: 9,
        ai: AiKind::Idle,
        first_floor: 63,
        score: 70,
    },
    MonsterKind {
        name: "Lesser Demon Lord",
        shape: Shape::Brute,
        primary: rgb(180, 40, 40),
        accent: rgb(220, 200, 40),
        max_hp: 110,
        skill: 18,
        evasion: 3,
        damage: 21,
        armor: 6,
        ai: AiKind::Smart,
        first_floor: 64,
        score: 80,
    },
    MonsterKind {
        name: "Death Knight",
        shape: Shape::Humanoid,
        primary: rgb(40, 40, 60),
        accent: rgb(200, 40, 40),
        max_hp: 110,
        skill: 19,
        evasion: 3,
        damage: 21,
        armor: 7,
        ai: AiKind::Smart,
        first_floor: 65,
        score: 84,
    },
    MonsterKind {
        name: "Lich",
        shape: Shape::Mage,
        primary: rgb(120, 60, 180),
        accent: rgb(60, 220, 200),
        max_hp: 100,
        skill: 20,
        evasion: 4,
        damage: 22,
        armor: 5,
        ai: AiKind::Ranged,
        first_floor: 66,
        score: 90,
    },
    MonsterKind {
        name: "Storm Giant",
        shape: Shape::Brute,
        primary: rgb(120, 140, 220),
        accent: rgb(220, 220, 60),
        max_hp: 130,
        skill: 17,
        evasion: 2,
        damage: 22,
        armor: 6,
        ai: AiKind::Smart,
        first_floor: 67,
        score: 90,
    },
    MonsterKind {
        name: "Beholder",
        shape: Shape::Boss,
        primary: rgb(140, 80, 80),
        accent: rgb(220, 220, 220),
        max_hp: 120,
        skill: 19,
        evasion: 4,
        damage: 22,
        armor: 6,
        ai: AiKind::Ranged,
        first_floor: 68,
        score: 90,
    },
    MonsterKind {
        name: "Fire Giant",
        shape: Shape::Brute,
        primary: rgb(220, 80, 40),
        accent: rgb(60, 60, 60),
        max_hp: 130,
        skill: 18,
        evasion: 2,
        damage: 24,
        armor: 7,
        ai: AiKind::Chaser,
        first_floor: 69,
        score: 96,
    },
    MonsterKind {
        name: "Frost Giant",
        shape: Shape::Brute,
        primary: rgb(200, 220, 240),
        accent: rgb(60, 60, 120),
        max_hp: 130,
        skill: 18,
        evasion: 2,
        damage: 24,
        armor: 7,
        ai: AiKind::Chaser,
        first_floor: 70,
        score: 96,
    },
    // -- Floors 71 through 80. Young dragons and dread powers. --
    MonsterKind {
        name: "Young White Dragon",
        shape: Shape::Dragon,
        primary: rgb(220, 220, 240),
        accent: rgb(120, 180, 220),
        max_hp: 140,
        skill: 19,
        evasion: 4,
        damage: 24,
        armor: 7,
        ai: AiKind::Fast,
        first_floor: 71,
        score: 110,
    },
    MonsterKind {
        name: "Young Black Dragon",
        shape: Shape::Dragon,
        primary: rgb(40, 40, 40),
        accent: rgb(180, 180, 60),
        max_hp: 150,
        skill: 19,
        evasion: 4,
        damage: 25,
        armor: 7,
        ai: AiKind::Fast,
        first_floor: 72,
        score: 112,
    },
    MonsterKind {
        name: "Young Green Dragon",
        shape: Shape::Dragon,
        primary: rgb(40, 160, 40),
        accent: rgb(220, 220, 40),
        max_hp: 150,
        skill: 19,
        evasion: 4,
        damage: 25,
        armor: 7,
        ai: AiKind::Fast,
        first_floor: 73,
        score: 112,
    },
    MonsterKind {
        name: "Young Blue Dragon",
        shape: Shape::Dragon,
        primary: rgb(40, 80, 220),
        accent: rgb(220, 220, 60),
        max_hp: 150,
        skill: 19,
        evasion: 4,
        damage: 26,
        armor: 7,
        ai: AiKind::Fast,
        first_floor: 74,
        score: 116,
    },
    MonsterKind {
        name: "Young Red Dragon",
        shape: Shape::Dragon,
        primary: rgb(220, 40, 40),
        accent: rgb(220, 180, 40),
        max_hp: 160,
        skill: 20,
        evasion: 4,
        damage: 26,
        armor: 7,
        ai: AiKind::Fast,
        first_floor: 75,
        score: 118,
    },
    MonsterKind {
        name: "Bone Devil",
        shape: Shape::Skeleton,
        primary: rgb(220, 220, 200),
        accent: rgb(180, 40, 40),
        max_hp: 140,
        skill: 20,
        evasion: 4,
        damage: 25,
        armor: 6,
        ai: AiKind::Smart,
        first_floor: 76,
        score: 116,
    },
    MonsterKind {
        name: "Mind Flayer",
        shape: Shape::Mage,
        primary: rgb(100, 100, 200),
        accent: rgb(220, 60, 140),
        max_hp: 130,
        skill: 21,
        evasion: 5,
        damage: 26,
        armor: 5,
        ai: AiKind::Ranged,
        first_floor: 77,
        score: 124,
    },
    MonsterKind {
        name: "Adult Black Dragon",
        shape: Shape::Dragon,
        primary: rgb(30, 30, 30),
        accent: rgb(160, 160, 60),
        max_hp: 180,
        skill: 21,
        evasion: 4,
        damage: 28,
        armor: 8,
        ai: AiKind::Smart,
        first_floor: 78,
        score: 140,
    },
    MonsterKind {
        name: "Adult Green Dragon",
        shape: Shape::Dragon,
        primary: rgb(30, 140, 30),
        accent: rgb(200, 200, 30),
        max_hp: 180,
        skill: 21,
        evasion: 4,
        damage: 28,
        armor: 8,
        ai: AiKind::Smart,
        first_floor: 79,
        score: 140,
    },
    MonsterKind {
        name: "Adult Blue Dragon",
        shape: Shape::Dragon,
        primary: rgb(30, 80, 200),
        accent: rgb(220, 220, 60),
        max_hp: 180,
        skill: 21,
        evasion: 4,
        damage: 28,
        armor: 8,
        ai: AiKind::Smart,
        first_floor: 80,
        score: 142,
    },
    // -- Floors 81 through 90. Adult dragons and dread elders. --
    MonsterKind {
        name: "Adult Red Dragon",
        shape: Shape::Dragon,
        primary: rgb(200, 30, 30),
        accent: rgb(220, 180, 30),
        max_hp: 200,
        skill: 22,
        evasion: 4,
        damage: 30,
        armor: 8,
        ai: AiKind::Smart,
        first_floor: 81,
        score: 150,
    },
    MonsterKind {
        name: "Adult White Dragon",
        shape: Shape::Dragon,
        primary: rgb(240, 240, 250),
        accent: rgb(100, 160, 220),
        max_hp: 200,
        skill: 22,
        evasion: 4,
        damage: 30,
        armor: 8,
        ai: AiKind::Smart,
        first_floor: 82,
        score: 150,
    },
    MonsterKind {
        name: "Ancient White Dragon",
        shape: Shape::Dragon,
        primary: rgb(240, 240, 250),
        accent: rgb(60, 120, 200),
        max_hp: 220,
        skill: 23,
        evasion: 4,
        damage: 32,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 83,
        score: 170,
    },
    MonsterKind {
        name: "Demon Lord",
        shape: Shape::Brute,
        primary: rgb(180, 40, 60),
        accent: rgb(40, 40, 60),
        max_hp: 220,
        skill: 23,
        evasion: 3,
        damage: 32,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 84,
        score: 170,
    },
    MonsterKind {
        name: "Pit Fiend",
        shape: Shape::Brute,
        primary: rgb(160, 30, 30),
        accent: rgb(220, 200, 40),
        max_hp: 240,
        skill: 23,
        evasion: 3,
        damage: 33,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 85,
        score: 180,
    },
    MonsterKind {
        name: "Beholder Tyrant",
        shape: Shape::Boss,
        primary: rgb(160, 60, 60),
        accent: rgb(220, 220, 220),
        max_hp: 220,
        skill: 22,
        evasion: 5,
        damage: 32,
        armor: 8,
        ai: AiKind::Ranged,
        first_floor: 86,
        score: 180,
    },
    MonsterKind {
        name: "Ancient Black Dragon",
        shape: Shape::Dragon,
        primary: rgb(20, 20, 20),
        accent: rgb(160, 160, 60),
        max_hp: 240,
        skill: 23,
        evasion: 4,
        damage: 34,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 87,
        score: 190,
    },
    MonsterKind {
        name: "Ancient Green Dragon",
        shape: Shape::Dragon,
        primary: rgb(20, 120, 20),
        accent: rgb(200, 200, 30),
        max_hp: 240,
        skill: 23,
        evasion: 4,
        damage: 34,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 88,
        score: 190,
    },
    MonsterKind {
        name: "Ancient Blue Dragon",
        shape: Shape::Dragon,
        primary: rgb(20, 60, 180),
        accent: rgb(220, 220, 60),
        max_hp: 240,
        skill: 23,
        evasion: 4,
        damage: 34,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 89,
        score: 190,
    },
    MonsterKind {
        name: "Ancient Red Dragon",
        shape: Shape::Dragon,
        primary: rgb(180, 20, 20),
        accent: rgb(220, 180, 30),
        max_hp: 260,
        skill: 24,
        evasion: 4,
        damage: 36,
        armor: 10,
        ai: AiKind::Smart,
        first_floor: 90,
        score: 200,
    },
    // -- Floors 91 through 100. Mythic beasts and the final guardian. --
    MonsterKind {
        name: "Tarrasque",
        shape: Shape::Boss,
        primary: rgb(140, 80, 40),
        accent: rgb(220, 60, 60),
        max_hp: 320,
        skill: 24,
        evasion: 1,
        damage: 40,
        armor: 12,
        ai: AiKind::Chaser,
        first_floor: 91,
        score: 240,
    },
    MonsterKind {
        name: "Empyrean",
        shape: Shape::Humanoid,
        primary: rgb(240, 220, 140),
        accent: rgb(220, 200, 40),
        max_hp: 280,
        skill: 25,
        evasion: 4,
        damage: 36,
        armor: 10,
        ai: AiKind::Smart,
        first_floor: 92,
        score: 240,
    },
    MonsterKind {
        name: "Solar",
        shape: Shape::Mage,
        primary: rgb(240, 220, 80),
        accent: rgb(240, 240, 240),
        max_hp: 280,
        skill: 26,
        evasion: 5,
        damage: 36,
        armor: 9,
        ai: AiKind::Ranged,
        first_floor: 93,
        score: 240,
    },
    MonsterKind {
        name: "Lich King",
        shape: Shape::Mage,
        primary: rgb(80, 60, 200),
        accent: rgb(40, 240, 220),
        max_hp: 280,
        skill: 26,
        evasion: 4,
        damage: 38,
        armor: 9,
        ai: AiKind::Smart,
        first_floor: 94,
        score: 260,
    },
    MonsterKind {
        name: "Ancient Wyrm",
        shape: Shape::Dragon,
        primary: rgb(220, 180, 60),
        accent: rgb(220, 80, 40),
        max_hp: 320,
        skill: 26,
        evasion: 4,
        damage: 40,
        armor: 10,
        ai: AiKind::Smart,
        first_floor: 95,
        score: 280,
    },
    MonsterKind {
        name: "Avatar of Destruction",
        shape: Shape::Boss,
        primary: rgb(220, 40, 40),
        accent: rgb(40, 40, 40),
        max_hp: 320,
        skill: 27,
        evasion: 3,
        damage: 42,
        armor: 11,
        ai: AiKind::Smart,
        first_floor: 96,
        score: 300,
    },
    MonsterKind {
        name: "World Devourer",
        shape: Shape::Boss,
        primary: rgb(60, 40, 40),
        accent: rgb(200, 60, 200),
        max_hp: 360,
        skill: 27,
        evasion: 2,
        damage: 44,
        armor: 12,
        ai: AiKind::Chaser,
        first_floor: 97,
        score: 320,
    },
    MonsterKind {
        name: "Cosmic Horror",
        shape: Shape::Boss,
        primary: rgb(40, 40, 80),
        accent: rgb(160, 60, 220),
        max_hp: 360,
        skill: 28,
        evasion: 4,
        damage: 44,
        armor: 11,
        ai: AiKind::Ranged,
        first_floor: 98,
        score: 320,
    },
    MonsterKind {
        name: "Elder God Spawn",
        shape: Shape::Boss,
        primary: rgb(80, 60, 100),
        accent: rgb(220, 220, 80),
        max_hp: 400,
        skill: 29,
        evasion: 3,
        damage: 46,
        armor: 12,
        ai: AiKind::Smart,
        first_floor: 99,
        score: 360,
    },
    MonsterKind {
        name: "Balrog Lord",
        shape: Shape::Boss,
        primary: rgb(60, 20, 20),
        accent: rgb(240, 80, 20),
        max_hp: 480,
        skill: 30,
        evasion: 3,
        damage: 50,
        armor: 13,
        ai: AiKind::Boss,
        first_floor: 100,
        score: 500,
    },
];

/// Convenience accessor. Returns `BESTIARY[kind]`, the caller is
/// responsible for keeping `kind` in range.
pub fn kind(kind: usize) -> &'static MonsterKind {
    &BESTIARY[kind]
}
