//! Shared kernel-construction code.
//!
//! The binaries call into [`three_task_kernel`] (or the
//! arena-sized variant) to get a fully-populated [`Kernel<P>`]
//! holding the LED, sensor, and heartbeat tasks. Each binary's
//! main function then runs the kernel through its platform's
//! executor (the tiny block-on for std, the embassy executor on
//! the N6).
//!
//! Two compilation modes coexist behind the `keleusma-compile`
//! feature.
//!
//! - **Source mode** (`keleusma-compile` on, default).
//!   The runtime carries the full compile pipeline. Task
//!   scripts are bundled as `include_str!` constants and
//!   tokenised, parsed, and compiled at boot inside
//!   [`build_module`]. The shared `prelude.kel` is prepended at
//!   compile time so every task sees the same `Status` and
//!   `StatusErrorCode` enum declarations.
//!
//! - **Precompiled-bytecode mode** (`keleusma-compile` off).
//!   The `build.rs` script invokes the parent crate's compile
//!   pipeline at host build time and emits one
//!   `OUT_DIR/<name>.kel.bin` per script. The runtime carries
//!   only the VM; task modules load through `Module::from_bytes`
//!   on the embedded `include_bytes!` constants.
//!
//! Verification of the loaded module is controlled by the
//! orthogonal `keleusma-verify` feature. `Vm::new` is always
//! called; the keleusma crate's `verify` feature decides
//! whether verification actually runs inside `Vm::new`. With
//! the feature off, `Vm::new` degrades silently to a trust-load,
//! shifting the bounded-memory contract onto whatever build-time
//! verification the artefact ingestion process performed.

use alloc::boxed::Box;
use alloc::format;
use alloc::string::String;

#[cfg(feature = "keleusma-compile")]
use keleusma::compiler::compile;
#[cfg(feature = "keleusma-compile")]
use keleusma::lexer::tokenize;
#[cfg(feature = "keleusma-compile")]
use keleusma::parser::parse;
use keleusma::vm::{DEFAULT_ARENA_CAPACITY, Vm};
use keleusma::{Arena, Module};

use crate::kernel::{Kernel, Task, TaskState, WakeReason};
use crate::natives::register_task_natives;
use crate::platform::Platform;

// --- Source-mode constants. Present only when the compile
// pipeline is in the runtime image. ---

/// Prelude prepended to every task source. Defines the
/// `Status` and `StatusErrorCode` enums shared with the host's
/// native surface. Kept here as a single source of truth so all
/// tasks see identical declarations. `pub` so the demonstrator
/// binaries can prepend the same text when computing per-task
/// WCET reports off-line (the prelude declares the symbols every
/// task script references, so compilation fails without it).
#[cfg(feature = "keleusma-compile")]
pub const PRELUDE: &str = include_str!("../scripts/prelude.kel");

/// LED blinker task source.
#[cfg(feature = "keleusma-compile")]
pub const SRC_LED: &str = include_str!("../scripts/led.kel");
/// Sensor poller task source.
#[cfg(feature = "keleusma-compile")]
pub const SRC_SENSOR: &str = include_str!("../scripts/sensor.kel");
/// Heartbeat task source.
#[cfg(feature = "keleusma-compile")]
pub const SRC_HEARTBEAT: &str = include_str!("../scripts/heartbeat.kel");
/// Event listener task source. Waits on event id 1.
#[cfg(feature = "keleusma-compile")]
pub const SRC_EVENT_LISTENER: &str = include_str!("../scripts/event_listener.kel");
/// Faulty task source. Triggers a `DivisionByZero` every fifth
/// iteration to exercise the supervised-restart policy.
#[cfg(feature = "keleusma-compile")]
pub const SRC_FAULTY: &str = include_str!("../scripts/faulty.kel");

// --- Precompiled-bytecode constants. Present only when the
// compile pipeline is absent and `build.rs` has produced
// bytecode artefacts in OUT_DIR. ---

/// LED blinker task bytecode.
#[cfg(not(feature = "keleusma-compile"))]
pub const BIN_LED: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/led.kel.bin"));
/// Sensor poller task bytecode.
#[cfg(not(feature = "keleusma-compile"))]
pub const BIN_SENSOR: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/sensor.kel.bin"));
/// Heartbeat task bytecode.
#[cfg(not(feature = "keleusma-compile"))]
pub const BIN_HEARTBEAT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/heartbeat.kel.bin"));
/// Event listener task bytecode.
#[cfg(not(feature = "keleusma-compile"))]
pub const BIN_EVENT_LISTENER: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/event_listener.kel.bin"));
/// Faulty task bytecode.
#[cfg(not(feature = "keleusma-compile"))]
pub const BIN_FAULTY: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/faulty.kel.bin"));

/// Signed bytecode fixture used by the boot-time
/// [`run_signed_self_test`] cryptographic self-test. Generated by
/// `build.rs` from `signed fn main() -> Word { 42 }` with the
/// hardcoded test seed `[0xA5; 32]`. Embeds the V0.2.0 wire
/// format including the 64-byte signature.
///
/// Requires the `keleusma-signatures` cargo feature.
#[cfg(feature = "keleusma-signatures")]
pub const BIN_SIGNED_SELF_TEST: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/signed_self_test.kel.bin"));

/// 32-byte Ed25519 verifying key matching the seed used to sign
/// [`BIN_SIGNED_SELF_TEST`].
///
/// Requires the `keleusma-signatures` cargo feature.
#[cfg(feature = "keleusma-signatures")]
pub const PUB_SIGNED_SELF_TEST: &[u8; 32] =
    include_bytes!(concat!(env!("OUT_DIR"), "/signed_self_test_pub.bin"));

/// Exercise the cryptographic verification path at boot. Decodes
/// the embedded verifying key, runs
/// [`keleusma::wire_format::verify_module_signature`] against the
/// embedded signed bytes, and returns the outcome so the caller
/// can log success or failure through defmt.
///
/// Hosts call this once at startup to confirm the signature
/// machinery links and runs on the target hardware. A failure
/// here means the firmware build is broken; the host should
/// refuse to enter the main scheduler loop.
///
/// Requires the `keleusma-signatures` cargo feature.
#[cfg(feature = "keleusma-signatures")]
pub fn run_signed_self_test() -> Result<(), &'static str> {
    let vk = ed25519_dalek::VerifyingKey::from_bytes(PUB_SIGNED_SELF_TEST)
        .map_err(|_| "self-test verifying key invalid")?;
    keleusma::wire_format::verify_module_signature(BIN_SIGNED_SELF_TEST, &[vk])
        .map_err(|_| "self-test signature did not verify")
}

/// Construct the demonstrator kernel for the given platform.
/// Returns a kernel with five cooperative tasks loaded and ready
/// to run. Uses [`keleusma::vm::DEFAULT_ARENA_CAPACITY`] for each
/// task; pass a smaller value to
/// [`three_task_kernel_with_arena_capacity`] for embedded targets
/// where heap budget is tight.
///
/// Tasks: `led` (toggles GPIO 13), `sensor` (polls channel 0),
/// `heartbeat` (logs every five seconds), `event_listener`
/// (waits on event id 1, exercises the ISR-to-task wake-up
/// pattern), and `faulty` (triggers `DivisionByZero` every fifth
/// iteration to exercise the supervised-restart policy).
///
/// The function leaks one arena per task; the kernel holds each
/// VM through a `'static` reference. The leak is a one-time
/// bounded allocation; the long-run behaviour is constant in
/// memory.
///
/// The function name retains the historical `three_task_kernel`
/// prefix for source compatibility; the surface now constructs
/// five tasks.
pub fn three_task_kernel<P: Platform>() -> Result<Kernel<P>, String> {
    three_task_kernel_with_arena_capacity::<P>(DEFAULT_ARENA_CAPACITY)
}

/// Same as [`three_task_kernel`] but with an explicit per-task
/// arena capacity. Embedded targets use this to fit the task
/// set within a constrained global heap; the std demonstrator
/// continues through the no-argument wrapper above. See
/// [`build_task_with_arena_capacity`] for the per-task path.
pub fn three_task_kernel_with_arena_capacity<P: Platform>(
    arena_capacity: usize,
) -> Result<Kernel<P>, String> {
    let mut kernel = Kernel::<P>::new();
    // Existing tasks: no WCET budget (the demonstrator does not
    // bound them) and no restart on Halt.
    #[cfg(feature = "keleusma-compile")]
    let (led_src, sensor_src, heartbeat_src, event_listener_src, faulty_src) = (
        SRC_LED,
        SRC_SENSOR,
        SRC_HEARTBEAT,
        SRC_EVENT_LISTENER,
        SRC_FAULTY,
    );
    #[cfg(not(feature = "keleusma-compile"))]
    let (led_src, sensor_src, heartbeat_src, event_listener_src, faulty_src) = (
        BIN_LED,
        BIN_SENSOR,
        BIN_HEARTBEAT,
        BIN_EVENT_LISTENER,
        BIN_FAULTY,
    );

    // Production-style admission control. The three legacy tasks
    // declare no WCET budget; their slices are small. The
    // event-listener and faulty tasks demonstrate the per-task
    // budget mechanism: pass `Some(budget)` to reject hot swaps
    // whose declared WCET exceeds the budget.
    kernel.add_task(build_task_full::<P>(
        "led",
        led_src,
        arena_capacity,
        None,
        0,
    )?);
    kernel.add_task(build_task_full::<P>(
        "sensor",
        sensor_src,
        arena_capacity,
        None,
        0,
    )?);
    kernel.add_task(build_task_full::<P>(
        "heartbeat",
        heartbeat_src,
        arena_capacity,
        None,
        0,
    )?);
    kernel.add_task(build_task_full::<P>(
        "event_listener",
        event_listener_src,
        arena_capacity,
        None,
        0,
    )?);
    // Faulty task carries a non-zero `max_restarts` so the
    // kernel's supervised-restart policy can be observed. The
    // value caps the recovery budget; once exhausted, subsequent
    // Halt errors mark the task `Finished`.
    kernel.add_task(build_task_full::<P>(
        "faulty",
        faulty_src,
        arena_capacity,
        None,
        16,
    )?);
    // Enable the internal event ticker. The kernel posts event
    // id 1 every 2500 ms, waking the `event_listener` task. This
    // is the demonstrator's stand-in for an interrupt source; a
    // real deployment disables the ticker and routes
    // `Kernel::post_event` from an ISR or a co-spawned host
    // task.
    kernel.enable_event_tick(1, 2500);
    Ok(kernel)
}

/// Compile or load a single task and wrap it as a kernel
/// [`Task`]. Convenience wrapper over
/// [`build_task_with_arena_capacity`] using
/// [`keleusma::vm::DEFAULT_ARENA_CAPACITY`].
///
/// The second parameter is either source text or precompiled
/// bytecode, depending on whether the `keleusma-compile`
/// feature is enabled.
#[cfg(feature = "keleusma-compile")]
pub fn build_task<P: Platform>(name: &'static str, src: &str) -> Result<Task, String> {
    build_task_with_arena_capacity::<P>(name, src, DEFAULT_ARENA_CAPACITY)
}

/// Precompiled-bytecode variant of [`build_task`]. See the
/// module-level documentation for the two compilation modes.
#[cfg(not(feature = "keleusma-compile"))]
pub fn build_task<P: Platform>(name: &'static str, bytes: &[u8]) -> Result<Task, String> {
    build_task_with_arena_capacity::<P>(name, bytes, DEFAULT_ARENA_CAPACITY)
}

/// Compile or load a single task and wrap it as a kernel
/// [`Task`] with an explicit arena capacity.
///
/// In source mode (`keleusma-compile` on) the second parameter
/// is the task source; the function prepends the shared
/// prelude and runs the parent's compile pipeline. In
/// precompiled-bytecode mode (`keleusma-compile` off) the
/// second parameter is the rkyv-archived bytecode produced by
/// `build.rs`; the function deserialises through
/// `Module::from_bytes`. Both modes converge on the same
/// downstream steps (arena leak, `Vm::new`, slot
/// initialisation, native registration).
#[cfg(feature = "keleusma-compile")]
pub fn build_task_with_arena_capacity<P: Platform>(
    name: &'static str,
    src: &str,
    arena_capacity: usize,
) -> Result<Task, String> {
    build_task_full::<P>(name, src, arena_capacity, None, 0)
}

#[cfg(not(feature = "keleusma-compile"))]
pub fn build_task_with_arena_capacity<P: Platform>(
    name: &'static str,
    bytes: &[u8],
    arena_capacity: usize,
) -> Result<Task, String> {
    build_task_full::<P>(name, bytes, arena_capacity, None, 0)
}

/// Build a task with the full set of admission and recovery
/// knobs: arena capacity, WCET budget (`None` accepts any
/// declared WCET), and the supervised-restart budget. The
/// shorter-signature variants above delegate here with default
/// values that match the legacy behaviour (unbounded WCET, no
/// restart on Halt).
#[cfg(feature = "keleusma-compile")]
pub fn build_task_full<P: Platform>(
    name: &'static str,
    src: &str,
    arena_capacity: usize,
    wcet_budget_cycles: Option<u32>,
    max_restarts: u32,
) -> Result<Task, String> {
    let module = build_module(src).map_err(|e| format!("build_module for {}: {}", name, e))?;
    finish_build_task::<P>(
        name,
        module,
        arena_capacity,
        wcet_budget_cycles,
        max_restarts,
    )
}

#[cfg(not(feature = "keleusma-compile"))]
pub fn build_task_full<P: Platform>(
    name: &'static str,
    bytes: &[u8],
    arena_capacity: usize,
    wcet_budget_cycles: Option<u32>,
    max_restarts: u32,
) -> Result<Task, String> {
    let module =
        Module::from_bytes(bytes).map_err(|e| format!("load_module for {}: {:?}", name, e))?;
    finish_build_task::<P>(
        name,
        module,
        arena_capacity,
        wcet_budget_cycles,
        max_restarts,
    )
}

/// Shared tail of [`build_task_with_arena_capacity`]. Validates
/// the loaded module's declared WCET against the supplied budget,
/// leaks an arena of the requested capacity, constructs the VM,
/// zeros the data segment, and registers the task native surface.
/// Called from both the source and precompiled variants.
///
/// `Vm::new` is called unconditionally. The keleusma crate's
/// `verify` feature, surfaced through this crate's
/// `keleusma-verify`, decides whether structural and
/// resource-bound verification runs inside `Vm::new`.
///
/// The WCET budget check rejects scripts whose declared
/// `module.wcet_cycles` exceeds the host-supplied budget before
/// any arena is allocated or any VM is constructed. The check is
/// the load-time half of the admission control story; the
/// matching swap-time half lives in `Kernel::replace_task`.
/// `None` disables the check (the loaded value is accepted
/// regardless). The same value is stored on the resulting `Task`
/// so subsequent hot swaps reuse it as the budget cap.
fn finish_build_task<P: Platform>(
    name: &'static str,
    module: Module,
    arena_capacity: usize,
    wcet_budget_cycles: Option<u32>,
    max_restarts: u32,
) -> Result<Task, String> {
    if let Some(budget) = wcet_budget_cycles
        && module.wcet_cycles > budget
    {
        return Err(alloc::format!(
            "task `{}`: declared WCET {} cycles exceeds budget {} cycles",
            name,
            module.wcet_cycles,
            budget
        ));
    }
    let arena: &'static Arena = Box::leak(Box::new(Arena::with_capacity(arena_capacity)));
    // The keleusma crate gates the checked `Vm::new` behind its `verify`
    // feature (audit finding 22): a safe constructor no longer silently
    // skips verification. With `keleusma-verify` enabled the checked path
    // runs structural and resource-bound verification; without it, the
    // verifier is not compiled, so construction goes through the explicit
    // `unsafe` trust-load.
    #[cfg(feature = "keleusma-verify")]
    let mut vm: Vm<'static, 'static> =
        Vm::new(module, arena).map_err(|e| format!("vm new for {}: {:?}", name, e))?;
    // SAFETY: with `keleusma-verify` off the host attests the bytecode's
    // structural soundness and worst-case resource bounds out of band -- the
    // precompiled bins emit bytecode through the verified build-time pipeline
    // (build.rs), and the WCET budget check above bounds declared cost. The
    // `unsafe` marker records the dropped runtime resource-bounds check.
    #[cfg(not(feature = "keleusma-verify"))]
    let mut vm: Vm<'static, 'static> = unsafe { Vm::new_unchecked(module, arena) }
        .map_err(|e| format!("vm new for {}: {:?}", name, e))?;
    // Host-owned shared-data buffer for this task, zeroed for the script's
    // first observation of each shared field (B28 item 2). Empty when the
    // task declares no shared data.
    let shared = alloc::vec![0u8; vm.shared_data_bytes()];
    // The utility natives that back f-string interpolation
    // (`to_string`, `concat`, `slice`, `length`, `println`) are
    // no longer registered. Task scripts compile without the
    // `text` surface feature and emit diagnostics through
    // `host::log_event(code, data)` instead of constructing
    // arena-resident strings, so the helpers would be dead
    // weight in the runtime image.
    register_task_natives::<P>(&mut vm);
    Ok(Task {
        name,
        vm,
        shared,
        state: TaskState::Ready(WakeReason::FirstRun),
        started: false,
        wcet_budget_cycles,
        max_restarts,
        restart_count: 0,
    })
}

/// Source-mode helper. Prepend the prelude to the task source
/// and run the parent's compile pipeline. Available only when
/// the `keleusma-compile` feature is enabled.
///
/// Line numbers in compile errors for task scripts are offset
/// by the prelude's line count; the prelude itself is small
/// enough that this is acceptable for the scaffold.
#[cfg(feature = "keleusma-compile")]
fn build_module(src: &str) -> Result<Module, String> {
    let combined = format!("{}\n{}", PRELUDE, src);
    let tokens = tokenize(&combined).map_err(|e| format!("lex error: {:?}", e))?;
    let program = parse(&tokens).map_err(|e| format!("parse error: {:?}", e))?;
    compile(&program).map_err(|e| format!("compile error: {:?}", e))
}
