//! **A BYTE QUOTIENT ONCE CARRIED NO WIDTH, AND SO COULD FEED NOTHING.**
//!
//! # The finding, and where it came from
//!
//! `Op::Div` and `Op::Mod` pushed `Width::Unknown` unconditionally. For a `Word`
//! division that is right — a word carries no packed width. **For a matched
//! `Byte` pair it was wrong by omission**: the reference divides two `Byte`s to a
//! `Byte`, and dropping that made every operation CONSUMING a byte quotient
//! refuse, because the generic arithmetic surface admits only a matched pair.
//!
//! Measured before the repair: **all nine byte-producing operations lowered
//! ALONE; only `/` and `%` refused once their result fed another operation.**
//! `+`, `-`, `*`, `band`, `bor` and `bxor` already propagated it.
//!
//! # Why no existing instrument could see it
//!
//! `scalar_operator_matrix.rs` enumerates 90 cells and `mixed_operand_matrix.rs`
//! 42, and **every one of them applies a single operator**. A width that is lost
//! on the way OUT of an operation is invisible until something consumes the
//! result. `backend_support_census.rs` is keyed by opcode NAME and probes `Word`,
//! where the behaviour is correct.
//!
//! **It was found by a generated expression tree, on its fourth program.** That
//! is the whole argument for generating subjects rather than enumerating them.
//!
//! # What the repair does and does not change
//!
//! A matched `Byte` pair gains the width; **every other combination keeps exactly
//! the `Unknown` it had**, so `Word` division is untouched and a `Fixed` operand
//! never reaches the arm at all, being refused above it. Verified by 1500
//! generated byte trees agreeing with the reference.

mod common;

fn refusal(src: &str) -> Option<String> {
    let m = common::build(src);
    keleusma_native::module_refusals(&m, keleusma_native::LowerOptions::default())
        .first()
        .map(|(_, e)| format!("{e:?}"))
}

fn wrap(inner: &str) -> String {
    format!("fn main(a: Word, b: Word) -> Word {{ ({inner}) as Word }}")
}

/// Every byte producer, alone and feeding a following operation.
const PRODUCERS: &[(&str, &str)] = &[
    ("add", "((a as Byte) + (b as Byte))"),
    ("sub", "((a as Byte) - (b as Byte))"),
    ("mul", "((a as Byte) * (b as Byte))"),
    ("div", "((a as Byte) / (b as Byte))"),
    ("mod", "((a as Byte) % (b as Byte))"),
    ("band", "((a as Byte) band (b as Byte))"),
    ("bor", "((a as Byte) bor (b as Byte))"),
    ("bxor", "((a as Byte) bxor (b as Byte))"),
    ("cast", "(a as Byte)"),
];

/// **The population is the producer list, not the two that were broken.**
///
/// A census keyed to what the analyst already noticed finds nothing they had not
/// already noticed — this package has recorded that twice. Every producer is
/// checked in both positions, so a future regression in any of them fails here.
#[test]
fn every_byte_producer_feeds_a_following_operation() {
    let mut broken = Vec::new();
    for (name, p) in PRODUCERS {
        if let Some(e) = refusal(&wrap(&format!("({p} + (b as Byte))"))) {
            broken.push((*name, e));
        }
    }
    assert!(
        broken.is_empty(),
        "byte producer(s) whose result cannot feed a following operation: \
         {broken:?}.\n\nThat is the defect this file records: a width lost on the \
         way OUT of an operation is invisible to every single-operator cell, and \
         shows only when something consumes the result. If this is a deliberate \
         narrowing, say which operand combination it covers and why refusing beats \
         propagating."
    );
}

/// **Non-vacuity: the producers must lower alone**, or the test above is
/// reporting a compile failure rather than a width gap.
#[test]
fn every_byte_producer_lowers_on_its_own() {
    let mut broken = Vec::new();
    for (name, p) in PRODUCERS {
        if let Some(e) = refusal(&wrap(p)) {
            broken.push((*name, e));
        }
    }
    assert!(
        broken.is_empty(),
        "byte producer(s) that do not even lower alone: {broken:?}. Then the \
         composition test says nothing about width propagation."
    );
}

/// **`Word` division must NOT have gained a width**, since a word carries none
/// and inventing one would mispack a composite built from a word quotient.
#[test]
fn word_division_still_carries_no_packed_width() {
    let src = "fn main(a: Word, b: Word) -> Word { (a / b) + b }";
    assert!(
        refusal(src).is_none(),
        "word division composed with addition now refuses; the repair was meant \
         to be narrow to a matched Byte pair and has reached the word path"
    );
}
